using System;
using CSharpAuthor.Expressions;
using Xunit;

namespace CSharpAuthor.Tests.Adversary;

/// <summary>
/// The constructs added after the preview1003 review, each compiled rather than string-matched.
/// </summary>
/// <remarks>
/// Every one of these was reported by more than one of the four generators built against
/// preview1003, and every one had the same workaround: format the text by hand and hand it to
/// <c>AddCode</c>, losing type tracking and indent management with it.
/// </remarks>
public class AddedConstructTests
{
    private static string Render(CSharpFileDefinition file) => Emit.File(file);

    private static CSharpFileDefinition File(out ClassDefinition host)
    {
        var file = new CSharpFileDefinition("Probe.Added");

        host = file.AddClass("Host");
        host.Modifiers = ComponentModifier.Public;

        return file;
    }

    /// <summary>
    /// The generated-file header, which has to be the first comment in the file.
    /// </summary>
    /// <remarks>
    /// Reported by three of the four generators. <c>Comment</c> writes <c>///</c>, which is XML and
    /// documents whatever follows it, so there was no way to write an ordinary <c>//</c> line - let
    /// alone one above the derived usings, which is the only place the marker does anything.
    /// </remarks>
    [Fact]
    public void AutoGeneratedHeaderIsWrittenAboveTheUsings()
    {
        var file = File(out var host);

        file.AddAutoGeneratedHeader();

        var field = host.AddField(TypeDefinition.Get(typeof(System.Text.StringBuilder)), "_builder");
        field.Modifiers = ComponentModifier.Private;

        var output = Render(file);

        Assert.StartsWith("// <auto-generated/>", output.TrimStart('﻿'));

        var header = output.IndexOf("// <auto-generated/>", StringComparison.Ordinal);
        var usingDirective = output.IndexOf("using System.Text;", StringComparison.Ordinal);

        Assert.True(usingDirective > header, "the header has to precede the derived usings");

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// An ordinary comment as a statement, at the block's indent.
    /// </summary>
    [Fact]
    public void LineCommentIsWrittenAtTheBlockIndent()
    {
        var file = File(out var host);

        var method = host.AddMethod("Go");
        method.Modifiers = ComponentModifier.Public;
        method.SetReturnType(typeof(void));
        method.AddLineComment("one\ntwo");

        var output = Render(file);

        Assert.Contains("            // one\n            // two", output.Replace("\r\n", "\n"));

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// A <c>lock</c>, which had no node and could not be faked with <c>AddCode</c> because that
    /// never opens a scope.
    /// </summary>
    [Fact]
    public void LockOpensAScope()
    {
        var file = File(out var host);

        var gate = host.AddField(typeof(object), "_gate");
        gate.Modifiers = ComponentModifier.Private | ComponentModifier.Readonly;
        gate.InitializeValue = CodeOutputComponent.Get("new object()");

        var count = host.AddField(typeof(int), "_count");
        count.Modifiers = ComponentModifier.Private;

        var method = host.AddMethod("Go");
        method.Modifiers = ComponentModifier.Public;
        method.SetReturnType(typeof(void));

        var guarded = method.Lock(Ex.Id("_gate"));
        guarded.AddIndentedStatement(Ex.Id("_count").Assign(Ex.Int(1)));

        var output = Render(file).Replace("\r\n", "\n");

        Assert.Contains("lock (_gate)\n", output);
        Assert.Contains("                _count = 1;", output);

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// A block with a caller-supplied header, for the constructs with no node of their own.
    /// </summary>
    [Fact]
    public void BlockOpensAScopeUnderItsHeader()
    {
        var file = File(out var host);

        var method = host.AddMethod("Go");
        method.Modifiers = ComponentModifier.Public;
        method.SetReturnType(typeof(void));

        var block = method.Block("checked");
        block.AddIndentedStatement(Ex.Id("_ = 1 + 1"));

        var output = Render(file).Replace("\r\n", "\n");

        Assert.Contains("checked\n", output);

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// <c>volatile</c>, which had no modifier at all.
    /// </summary>
    /// <remarks>
    /// Worth more than its size: a generated double-checked lock without it is correct on x86 and
    /// racy on ARM64.
    /// </remarks>
    [Fact]
    public void VolatileFieldIsWritten()
    {
        var file = File(out var host);

        var field = host.AddField(typeof(int), "_state");
        field.Modifiers = ComponentModifier.Private | ComponentModifier.Static | ComponentModifier.Volatile;

        var output = Render(file);

        Assert.Contains("private static volatile int _state;", output);

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// Named attribute arguments, which had to be pre-formatted as text.
    /// </summary>
    /// <remarks>
    /// They are held separately from the positional ones because C# requires every positional
    /// argument to precede every named one, and a name is an identifier - so it is escaped.
    /// </remarks>
    [Fact]
    public void NamedAttributeArgumentsFollowThePositionalOnes()
    {
        var file = File(out var host);

        host.AddBaseType(TypeDefinition.Get(typeof(Attribute)));

        // AllowMultiple is a read-write property, which is what C# requires of a named argument -
        // ObsoleteAttribute.IsError is read-only and is CS0617, which is exactly the kind of thing
        // compiling the output catches and a string assertion does not.
        host.AddAttribute(
                typeof(AttributeUsageAttribute),
                SyntaxHelpers.Property(TypeDefinition.Get(typeof(AttributeTargets)), "Class"))
            .AddNamedArgument("AllowMultiple", CodeOutputComponent.Get("true"));

        var output = Render(file);

        Assert.Contains("[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]", output);

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// A named argument whose name is a keyword is escaped like any other identifier.
    /// </summary>
    [Fact]
    public void NamedAttributeArgumentNameIsEscaped()
    {
        var file = File(out var host);

        host.AddAttribute(TypeDefinition.Get("Probe.Added", "MarkerAttribute"))
            .AddNamedArgument("class", CodeOutputComponent.Get("1"));

        Assert.Contains("@class = 1", Render(file));
    }

    /// <summary>
    /// The loop keywords are spaced like every other keyword that takes a parenthesis.
    /// </summary>
    /// <remarks>
    /// <c>if (</c> and <c>switch (</c> had the space; <c>for(</c>, <c>foreach(</c> and
    /// <c>while(</c> did not, in the same emitted file.
    /// </remarks>
    [Fact]
    public void LoopKeywordsAreSpacedLikeTheOthers()
    {
        var file = File(out var host);

        var method = host.AddMethod("Go");
        method.Modifiers = ComponentModifier.Public;
        method.SetReturnType(typeof(void));
        method.AddParameter(TypeDefinition.IEnumerable(typeof(string)), "items");

        method.ForEach("item", CodeOutputComponent.Get("items"));
        method.For("i", 0, 3);
        method.While(CodeOutputComponent.Get("false"));
        method.If(CodeOutputComponent.Get("true"));

        var output = Render(file);

        Assert.Contains("foreach (var item in items)", output);
        Assert.Contains("for (var i = 0;", output);
        Assert.Contains("while (false)", output);
        Assert.Contains("if (true)", output);

        Assert.DoesNotContain("foreach(", output);
        Assert.DoesNotContain("for(", output);
        Assert.DoesNotContain("while(", output);

        RoslynAssert.Compiles(output);
    }

    /// <summary>
    /// A documented field indents its comment like every other member kind.
    /// </summary>
    /// <remarks>
    /// <c>FieldDefinition</c> was the only one of eleven writing through <c>WriteLine</c> rather
    /// than <c>WriteIndentedLine</c>, so a documented field in a nested type had its <c>///</c>
    /// hard against the left margin.
    /// </remarks>
    [Fact]
    public void FieldCommentIsIndentedWithItsMember()
    {
        var file = File(out var host);

        var nested = host.AddClass("Nested");
        nested.Modifiers = ComponentModifier.Public;

        var field = nested.AddField(typeof(int), "_depth");
        field.Modifiers = ComponentModifier.Private;
        field.Comment = "how deep";

        var output = Render(file).Replace("\r\n", "\n");

        Assert.Contains("            /// <summary>", output);
        Assert.DoesNotContain("\n/// <summary>", output);
    }

    /// <summary>
    /// Members that render as <c>public</c> are grouped together, whichever modifier said so.
    /// </summary>
    /// <remarks>
    /// The grouping asked whether the <see cref="ComponentModifier.Public"/> flag was set; the
    /// writer asks <c>GetAccessibilityKeywords</c>, which returns <c>public</c> for a member with
    /// no accessibility flag at all. So <see cref="ComponentModifier.None"/> was written
    /// <c>public</c> and sorted with the private half, and two members that read identically ended
    /// up in different parts of the file with the private ones between them.
    /// </remarks>
    [Fact]
    public void MembersThatRenderPublicAreGroupedTogether()
    {
        var file = File(out var host);

        var noneMethod = host.AddMethod("FromNone");
        noneMethod.Modifiers = ComponentModifier.None;
        noneMethod.SetReturnType(typeof(void));

        var publicMethod = host.AddMethod("FromPublic");
        publicMethod.Modifiers = ComponentModifier.Public;
        publicMethod.SetReturnType(typeof(void));

        var privateMethod = host.AddMethod("FromPrivate");
        privateMethod.Modifiers = ComponentModifier.Private;
        privateMethod.SetReturnType(typeof(void));

        var output = Render(file);

        var none = output.IndexOf("FromNone", StringComparison.Ordinal);
        var pub = output.IndexOf("FromPublic", StringComparison.Ordinal);
        var priv = output.IndexOf("FromPrivate", StringComparison.Ordinal);

        Assert.True(none >= 0 && pub >= 0 && priv >= 0);

        // The two that render `public` are adjacent - the private one is not between them.
        Assert.True(
            (priv < none && priv < pub) || (priv > none && priv > pub),
            "a member that renders private must not sit between two that render public");

        RoslynAssert.Compiles(output);
    }
}
