import json, re, sys

nodes = json.load(open('nodes.json'))
TOK = json.load(open('tokens.json'))

CATS = ('ExpressionSyntax','StatementSyntax','PatternSyntax','MemberDeclarationSyntax',
        'TypeSyntax','VariableDesignationSyntax','SwitchLabelSyntax','QueryClauseSyntax',
        'InterpolatedStringContentSyntax','CollectionElementSyntax','BaseTypeSyntax',
        'DirectiveTriviaSyntax','XmlNodeSyntax','XmlAttributeSyntax','CrefSyntax',
        'TypeParameterConstraintSyntax','MemberCrefSyntax','SelectOrGroupClauseSyntax')

byname = {n['name']: n for n in nodes}

def iface(n):
    for c in n['chain']:
        if c in CATS:
            return 'I' + c.replace('Syntax', '')
    return 'ISyntax'

def iface_for_typename(t):
    if t in byname:
        return iface(byname[t])
    if t in CATS:
        return 'I' + t.replace('Syntax', '')
    return 'ISyntax'

# Nodes whose text is a value, not a fixed token — these stay hand-written.
HAND = {'IdentifierNameSyntax','LiteralExpressionSyntax','InterpolatedStringTextSyntax',
        'XmlTextSyntax','OmittedTypeArgumentSyntax','OmittedArraySizeExpressionSyntax',
        'BadDirectiveTriviaSyntax','XmlProcessingInstructionSyntax'}

KEYWORDS = set('''base this object operator default ref out in params new is event using while for if else
lock checked static class string int bool byte long short void return switch case try catch finally throw
do goto fixed unsafe var when where from select let join on equals by into with yield partial global type
value name double float decimal char sbyte uint ulong ushort nint nuint delegate enum struct interface
namespace public private protected internal abstract sealed virtual override readonly const volatile
extern explicit implicit unchecked sizeof typeof stackalloc as null true false'''.split())

def safe(name):
    lo = name[0].lower() + name[1:]
    return '@' + lo if lo in KEYWORDS else lo

out = []
w = out.append
w("// <auto-generated> Generated from Roslyn's Syntax.xml. Do not edit by hand.")
w("// Field order in the grammar IS emit order; that is the whole trick.")
w("#nullable enable")
w("using System.Collections.Generic;")
w("using CSharpAuthor;")
w("")
w("namespace GeneratedGrammar.Full;")
w("")
w("public interface ISyntax : IOutputComponent { }")
for i in sorted({iface(n) for n in nodes} - {'ISyntax'}):
    w(f"public interface {i} : ISyntax {{ }}")
w("")
w("""/// <summary>
/// The one thing the grammar does not encode: spacing. Word-like tokens need
/// separation from an adjacent identifier; punctuation does not.
/// </summary>
internal static class Tk
{
    public static void W(IOutputContext c, string t)
    {
        if (string.IsNullOrEmpty(t)) return;
        var word = char.IsLetter(t[0]);
        if (word && c.LastCharacter is char p &&
            (char.IsLetterOrDigit(p) || p == '_' || p == ')' || p == ']' || p == '}'))
            c.WriteSpace();
        c.Write(t);
        if (word) c.WriteSpace();
    }
}
""")

used = set()
generated = 0
kindparam = 0
for n in nodes:
    if n['name'] in HAND:
        continue
    cls = n['name'].replace('Syntax', '')
    if cls in used:
        cls += 'Node'
    used.add(cls)
    it = iface(n)
    props, ctor, assign, body = [], [], [], []
    has_kind_param = False

    for f in n['fields']:
        fn, ft, opt, kinds = f['name'], f['type'], f['opt'], f['kinds']
        lo = safe(fn)

        if ft == 'SyntaxToken':
            if len(kinds) == 1 and kinds[0] in TOK:
                body.append(f'        Tk.W(outputContext, {json.dumps(TOK[kinds[0]])});')
            else:
                has_kind_param = True
                props.append(f'    public string {fn} {{ get; set; }}')
                ctor.append(f'string {lo}')
                assign.append(f'        {fn} = {lo};')
                body.append(f'        Tk.W(outputContext, {fn});')
            continue

        if ft.startswith('SeparatedSyntaxList') or ft.startswith('SyntaxList'):
            inner = ft[ft.index('<') + 1:-1]
            et = iface_for_typename(inner)
            sep = ft.startswith('Separated')
            props.append(f'    public List<{et}> {fn} {{ get; }} = new();')
            joiner = '            if (i > 0) outputContext.Write(", ");\n' if sep else ''
            body.append(f'        for (var i = 0; i < {fn}.Count; i++)\n        {{\n{joiner}            {fn}[i].WriteOutput(outputContext);\n        }}')
            continue

        if ft in ('TypeSyntax', 'NameSyntax', 'SimpleNameSyntax', 'IdentifierNameSyntax'):
            # THE deferral point — handed to the context unrendered.
            props.append(f'    public ITypeDefinition? {fn} {{ get; set; }}')
            if not opt:
                ctor.append(f'ITypeDefinition {lo}')
                assign.append(f'        {fn} = {lo};')
            body.append(f'        if ({fn} != null) outputContext.Write({fn});')
            continue

        et = iface_for_typename(ft)
        props.append(f'    public {et}? {fn} {{ get; set; }}')
        if not opt:
            ctor.append(f'{et} {lo}')
            assign.append(f'        {fn} = {lo};')
        body.append(f'        {fn}?.WriteOutput(outputContext);')

    if has_kind_param:
        kindparam += 1

    w(f'public sealed class {cls} : {it}')
    w('{')
    for p in props:
        w(p)
    if props:
        w('')
    if ctor:
        w(f'    public {cls}({", ".join(ctor)})')
        w('    {')
        for a in assign:
            w(a)
        w('    }')
    else:
        w(f'    public {cls}() {{ }}')
    w('')
    w('    public void AddUsingNamespace(string ns) { }')
    w('')
    w('    public void WriteOutput(IOutputContext outputContext)')
    w('    {')
    for b in body:
        w(b)
    w('    }')
    w('}')
    w('')
    generated += 1

open('fullgen/Nodes.cs', 'w').write('\n'.join(out))
print(f"generated   : {generated} node classes", file=sys.stderr)
print(f"kind-param  : {kindparam} needed an operator/keyword argument", file=sys.stderr)
print(f"hand-written: {len(HAND)} ({', '.join(sorted(HAND))})", file=sys.stderr)
print(f"lines       : {len(out)}", file=sys.stderr)
