environment:
  build_version: 1.1.1000
  Version: $(build_version)
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore CSharpAuthor.sln
build:
  project: CSharpAuthor.sln
  publish_nuget: true
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.tests.dll'
artifacts:
- path: CSharpAuthor*.nupkg
  name: CSharpAuthor
image:
- Visual Studio 2022

