namespace CSharpAuthor;

/// <summary>
/// An ordinary <c>//</c> comment, one line per line of text.
/// </summary>
/// <remarks>
/// <para>
/// Distinct from <see cref="BaseOutputComponent.Comment"/>, which writes a <c>///</c> documentation
/// comment and is XML. This writes the other kind: a note to a reader, a header, anything that is
/// not documentation and must not be parsed as XML.
/// </para>
/// <para>
/// The most common use is the generated-file header, which is what
/// <see cref="SyntaxHelpers.AddAutoGeneratedHeader"/> writes. Every generator needs one - it is
/// what tells the compiler's analyzers, and most style tools, not to report on the file - and
/// before this component existed the only way to emit one was to hand the text to
/// <c>AddCode</c> and hope it landed above the usings.
/// </para>
/// </remarks>
public class LineCommentComponent : BaseOutputComponent
{
    private readonly string _comment;

    /// <summary>
    /// A comment whose text is <paramref name="comment"/>. A <c>\n</c> in it starts a new
    /// <c>//</c> line, at the same indent.
    /// </summary>
    public LineCommentComponent(string? comment)
    {
        _comment = comment ?? "";
    }

    protected override void WriteComponentOutput(IOutputContext outputContext)
    {
        foreach (var line in _comment.Split('\n'))
        {
            var text = line.TrimEnd('\r').TrimEnd();

            // A blank line keeps its marker but not a trailing space, matching how the
            // documentation comment writer treats one.
            outputContext.WriteIndentedLine(text.Length == 0 ? "//" : "// " + text);
        }
    }
}
